# Generated by Django 2.2 on 2020-10-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('period', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Weather Data',
            },
        ),
    ]
