# Generated by Django 2.2 on 2020-10-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201013_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
